# -*- coding: utf-8 -*-
"""Untitled1.ipynb
 
Automatically generated by Colaboratory.
 
Original file is located at
    https://colab.research.google.com/drive/1zFzHQ7Ul4PlKS0MAdBeS9mMoST-f8GgR
"""
 
import numpy as np
import matplotlib.pyplot as plt
 
t = np.arange(0,1,0.01)
xt = np.sin(2*np.pi*3*t)
plt.stem(t,xt)
 
t = np.arange(0,1,0.01)
xt = np.sin(2*np.pi*3*t)
plt.plot(t,xt)
 
n = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
xn = []
for i in range(-5,6):
  if i >= 0:
    xn.append(1)
  else :
    xn.append(0)
plt.title('Unit up signal')
plt.xlabel('n')
plt.ylabel('amplitude')
plt.stem(n,xn)
 
n = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
xn = []
for i in range(-5,6):
  if i >= 0:
    xn.append(i)
  else :
    xn.append(0)
plt.title('Unit ramp signal')
plt.xlabel('n')
plt.ylabel('amplitude')
plt.stem(n,xn)
 
n = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
xn = [0,1,2,3,4,5,4,3,2,1,0]
# for i in range(-5,6):
#   if i >= 0:
#     xn.append(i)
#   else :
#     xn.append(0)
plt.title('Unit signal')
plt.xlabel('n')
plt.ylabel('amplitude')
plt.stem(n,xn)
 
#delay...
n = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
xn = [0,1,2,3,4,5,4,3,2,1,0]
delay = 2
n = n[:len(n) - delay]
for i in range(0,delay):
  n.insert(0 , n[0]-1)
plt.title('Unit signal')
plt.xlabel('n')
plt.ylabel('amplitude')
plt.stem(n,xn)
 
#advance
n = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
xn = [0,1,2,3,4,5,4,3,2,1,0]
advance = 3
n = n[advance:len(n)]
for i in range(0,advance):
  n.append(n[-1]+1)
plt.title('Unit signal')
plt.xlabel('n')
plt.ylabel('amplitude')
plt.stem(n,xn)
 
n = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
x1n = [0,0,0,0,0,1,1,1,1,1,1]
x2n = [1,1,1,1,1,1,0,0,0,0,0]
y = np.add(x1n,x2n)
plt.subplot(3,1,1)
plt.stem(n,x1n)
plt.title('Input: x1')
 
plt.subplot(3,1,2)
plt.stem(n,x2n)
plt.title('Input: x2')
 
plt.subplot(3,1,3)
plt.stem(n,y)
plt.title('Input: y')
 
n = [-5,-4,-3,-2,-1,0,1,2,3,4,5]
x1n = [0,0,0,0,0,1,1,1,1,1,1]
x2n = [1,1,1,1,1,1,0,0,0,0,0]
y = np.multiply(x1n,x2n)
plt.subplot(3,1,1)
plt.stem(n,x1n)
plt.title('Input: x1')
 
plt.subplot(3,1,2)
plt.stem(n,x2n)
plt.title('Input: x2')
 
plt.subplot(3,1,3)
plt.stem(n,y)
plt.title('Input: y')
 